services:
  nginx:
    container_name: gallery-nginx
    build: 
      context: './services/nginx'
    networks:
      - gallery-network
    ports:
      - '8000:8080'
    volumes:
      - 'nginx_logs_data:/opt/bitnami/nginx/logs' 

  gallery-service:
    container_name: gallery-service
    build:
      context: ./services/gallery
    networks:
      - gallery-network
    environment:
      - PROJECT_TITLE=gallery
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USER=$MINIO_USER
      - MINIO_PASSWORD=$MINIO_PASSWORD

  minio:
    container_name: gallery-minio
    build:
      context: './services/minio'
    networks:
      - gallery-network
    environment:
      - MINIO_ROOT_USER=$MINIO_USER
      - MINIO_ROOT_PASSWORD=$MINIO_PASSWORD
    volumes:
      - 'minio_data:/data'
    ports:
      - '9000:9000'
      - '9001:9001'

networks:
  gallery-network:

volumes:
  nginx_logs_data:
  minio_data: