"""Add unique columns

Revision ID: 3947e5b5f2e6
Revises: 1250b5ff06f6
Create Date: 2025-06-18 17:14:54.917446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3947e5b5f2e6'
down_revision: Union[str, None] = '1250b5ff06f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_users_email',
        'users',
        ['email'],
        schema='auth'
    )
    op.create_unique_constraint(
        'uq_users_username',
        'users',
        ['username'],
        schema='auth'
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
